name: Workflow - Feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build_apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - run: |
          KEYSTORE_P12_ASC_FILE="keystore.asc"
          echo "${{ secrets.KEYSTORE_P12}}">>"${KEYSTORE_P12_ASC_FILE}"
          gpg \
            -d \
            --batch \
            --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_P12_ASC_FILE}"> "keystore.p12"
      - run: |
          KEYSTORE_PROPERTIES_ASC_FILE="keystore_properties.asc"
          echo "${{ secrets.KEYSTORE_PROPERTIES}}">>"${KEYSTORE_PROPERTIES_ASC_FILE}"
          gpg \
            -d \
            --batch \
            --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_PROPERTIES_ASC_FILE}"> "keystore.properties"
      - run: |
          MARVEL_API_KEYS_ASC_FILE="marvel_api_keys_properties.asc"
          echo "${{ secrets.KEYSTORE_PROPERTIES}}">>"${MARVEL_API_KEYS_ASC_FILE}"
          gpg \
            -d \
            --batch \
            --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${MARVEL_API_KEYS_ASC_FILE}"> "marvel_api_keys.properties"
      - run: ./gradlew -Pversion.buildNumber="${GITHUB_RUN_NUMBER}" assembleDevelopmentRelease
      - uses: actions/upload-artifact@v3
        with:
          name: development-release-apk
          path: app/build/outputs/apk/development/release/app-development-release.apk